/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.gradle.toolchains.foojay

import org.gradle.api.initialization.Settings
import org.gradle.jvm.toolchain.JavaToolchainResolverRegistry
import org.gradle.kotlin.dsl.support.serviceOf
import org.gradle.util.GradleVersion

@Suppress("unused", "UnstableApiUsage")
abstract class FoojayToolchainsPlugin: AbstractFoojayToolchainPlugin() {

    @Suppress("TooGenericExceptionThrown")
    override fun apply(settings: Settings) {
        if (GradleVersion.current().baseVersion < GradleVersion.version("7.6")) {
            throw RuntimeException("${FoojayToolchainsPlugin::class.simpleName} needs Gradle version 7.6 or higher")
        }
        settings.plugins.apply("jvm-toolchain-management")
        settings.serviceOf<JavaToolchainResolverRegistry>()
            .apply { register(FoojayToolchainResolver::class.java) }
    }
}
