/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.gradle.disco

import org.gradle.jvm.toolchain.JvmVendorSpec
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

class DiscoApiTest {

    private val api = DiscoApi()

    @Test
    fun `can resolve arbitrary vendors`() {
        assertEquals("ZuluPrime", api.resolveVendor(JvmVendorSpec.matching("zuluprime")))
        assertEquals("ZuluPrime", api.resolveVendor(JvmVendorSpec.matching("zUluprIme")))
    }

    @Test
    fun `can resolve pre-set vendors`() {
        assertEquals("Zulu", api.resolveVendor(JvmVendorSpec.AZUL))
        assertEquals("AOJ", api.resolveVendor(JvmVendorSpec.ADOPTOPENJDK))
        assertEquals("Temurin", api.resolveVendor(JvmVendorSpec.ADOPTIUM))
        assertEquals("Corretto", api.resolveVendor(JvmVendorSpec.AMAZON))
        assertEquals("Liberica", api.resolveVendor(JvmVendorSpec.BELLSOFT))
        assertEquals("Semeru", api.resolveVendor(JvmVendorSpec.IBM_SEMERU))
        assertEquals("Microsoft", api.resolveVendor(JvmVendorSpec.MICROSOFT))
        assertEquals("Oracle", api.resolveVendor(JvmVendorSpec.ORACLE))
        assertEquals("SAP Machine", api.resolveVendor(JvmVendorSpec.SAP))

        assertNull(api.resolveVendor(JvmVendorSpec.APPLE))
        assertNull(api.resolveVendor(JvmVendorSpec.GRAAL_VM))
        assertNull(api.resolveVendor(JvmVendorSpec.HEWLETT_PACKARD))
        assertNull(api.resolveVendor(JvmVendorSpec.IBM))
    }

    @Test
    fun `can match GraalVM`() {
        assertEquals("Graal VM CE 8", api.resolveVendor(JvmVendorSpec.matching("GraalVMCE8")))
        assertEquals("Graal VM CE 11", api.resolveVendor(JvmVendorSpec.matching("GraalVMCE11")))
    }

}
