/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.gradle.disco

import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.Test

class DiscoToolchainsPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can run task`() { //todo: dummy init test
        /*// Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('org.gradle.disco-toolchains')
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("greeting")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'org.gradle.disco-toolchains'"))*/
    }
}
