name: Dependency review for pull requests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::992382829881:role/GHASecrets_foojay-toolchains_all
        aws-region: "eu-central-1"
    - name: Get secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          DEVELOCITY_ACCESS_KEY, gha/foojay-toolchains/_all/DEVELOCITY_ACCESS_KEY
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4

    - name: Perform dependency review
      uses: actions/dependency-review-action@v4
